import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import { ViewSource } from './_components/view-source';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, modal }: { children: React.ReactNode; modal: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ViewSource linkUrl='https://github.com/noripi10' />
        <Providers>
          {children}
          {modal}
        </Providers>
      </body>
    </html>
  );
}
